### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by jasonsaayman**
Fix up the build process that seems to be failing

### CODE REVIEW

**Comment by codemaster138** [comment]
@jasonsaayman Where did this fail? This step is required to publish the outdated site...

**Comment by jasonsaayman** [comment]
@codemaster138 it fails on commit and push. The process is trying to push to master and that is not allowed

**Comment by codemaster138** [comment]
@jasonsaayman Ok, I see. I wrote that script back when I thought the site would be hosted on GH Pages, but since it won't be, that commit & push step is, of course, unnecessary.

However, the former is only true if netlify takes over the task of building the site. Do you have a netlify build script set up, or should I add a `package.json` with the necessary config to build inert on netlify?

**Comment by jasonsaayman** [comment]
@codemaster138 you can add, please :) I am currently pretty busy with a refactor of the main axios' packages test suite.

**Comment by codemaster138** [comment]
@jasonsaayman Will do!

**Comment by codemaster138** [comment]
@jsonsaayman I have made a PR (#19). AFAIK, after you merge you will have to set up the build command in the netlify dashboard. I have put instructions in the end of the PR.

**Pull request merged**
