### PR TITLE
[Added] Dark Theme & Animation in HomePage

### PR DESCRIPTION
**Pull request by ylyra**
I saw that the variables.scss file has a "dark theme" config, so I created the functionality along with adding some animation in the homepage preview script

Since all images was been imported using img tag I had to change the importation to svg so I could set the color of the images depending in which theme the user was using (only made this in post.ejs)

CPT2105182252-1282x511

Preview of the new animation \/
CPT2105182308-343x157

### CODE REVIEW

**Comment by codemaster138** [comment]
This looks great, but there's a few little things I don't like:

1. The cursor keeps blinking after the animation has finished. Maybe it should fade away?
2. The dark theme slider doesn't quite fit in with the looks of the site
3. Also, while I know the markup isn't the most beautiful, I kinda liked that the whole thing worked without javascript

**Comment by codemaster138** [comment]
Okay, I've updated the style of the button to match the theme of the site a little better and rebased the repo on the latest commit. @ylyra I'll make a PR on your fork

**Comment by ylyra** [comment]
@codemaster138 I updated the animation so the cursor could removed 3 seconds after been completed

**Comment by codemaster138** [comment]
@ylyra Great! @jasonsaayman Will merge this soon.

**Comment by jasonsaayman** [comment]
@codemaster138 can you please resolve the conflict? Thanks

**Comment by codemaster138** [comment]
@ylyra I've been trying to rebase your branch there's something wrong with the way I have my git set up to handle PRs so it's just rebasing off of random old commits and I just can't figure out why (Ah, yes, the pleasures of git)

Can you try to rebase your branch off of upstream/master (just accept all your changes)? That should fix the problem

**Comment by ylyra** [comment]
@codemaster138 I fixed the conflict, see if everything its ok now? please

**Comment by jasonsaayman** [comment]
Looks good on the preview 👍

**Pull request merged**
