### PR TITLE
Upgrade to inert v2

### PR DESCRIPTION
**Pull request by codemaster138**
I had a lot of time on my hands today, so I decided to translate the entire repo to Version 2 of inert, the static site generator it is built on.

Inert 2 contains a few nice new features, like image optimization, and is also a _lot_ more configurable.

The most drastic changes in this PR are probably the changes to the i18n system. In fact, the translation "guide" [here](https://github.com/axios/axios/issues/3505#issuecomment-756799340) is now completely obsolete. I will write a translation guide and publish it in a subsequent PR, but I'm not sure I'll get around to it today

### CODE REVIEW

**Comment by codemaster138** [comment]
@jasonsaayman Because I removed the actions, that "check" job will never complete. You can just merge the PR anyway

**Comment by codemaster138** [comment]
@jasonsaayman Is there anything holding you up on merging this?

**Comment by jasonsaayman** [comment]
I will merge once you have that new guide in. I will remove the offending check from our CI.

**Comment by codemaster138** [comment]
Ok

**Comment by jasonsaayman** [comment]
I have remove the check that would never pass

**Comment by codemaster138** [comment]
Hey @jasonsaayman, looks like I won't get around to writing that guide for a while... It's at the top of my to-do list, but I'm pretty busy right now, so maybe you should merge this to avoid conflicts with future pull requests, and I'll open a new PR to add the translation guide...

**Review by jasonsaayman — COMMENTED** [review]
👍

**Pull request merged**
